name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  http: ^0.13.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  video_player: ^2.7.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  fl_chart: ^0.66.0
  audioplayers: ^5.2.1
  video_compress: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/remove_ui.png
    - assets/sounds/start_sound.wav
