name: Deploy to EC2

on:
  push:
    branches: [ Release ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu/2025-1-CSC4004-1-3-Upper-Bound
          git fetch origin
          git reset --hard orgin/Release
          git clean -fd
          
          cd backend/getpushup/
          npm install
          npm run build
          fuser -k 3000/tcp || true
          npm run start &
